name: tikboo autopilot run

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'url'
        required: true
      folder:
        description: 'slozky: adult / insta'
        required: true
        type: choice
        options:
          - adult
          - insta

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: engine
        run: |
          pip install --upgrade yt-dlp boto3

      - name: execute
        env:
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          python autopilot.py "${{ github.event.inputs.video_url }}" "${{ github.event.inputs.folder }}"
